plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

java {
    sourceCompatibility = '21'
}

dependencies {
    // Importa as entidades, repositórios e as ferramentas do módulo base
    implementation project(':core')

    // Dependência exclusiva do Painel para gerar relatórios PDF
    implementation 'com.itextpdf:itext7-core:7.2.5'
}