# ===================================================================
# CONFIGURAÇÃO GERAL DA APLICAÇÃO - ADMIN API
# ===================================================================
spring.application.name=conectaavida-admin-api
server.port=8080

# ===================================================================
# CONFIGURAÇÃO SUPABASE - MODO SESSÃO (AWS-1 SÃO PAULO)
# ===================================================================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.pborxjuuexiqollesfxw
spring.datasource.password=ConectaVida_@2121
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE E FLYWAY
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Flyway ativado e configurado para criar a baseline
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jpa.open-in-view=true

# ===================================================================
# ALTA PERFORMANCE (JAVA 21)
# ===================================================================
spring.threads.virtual.enabled=true

# ===================================================================
# CONFIGURAÇÕES DE ENVIO DE E-MAIL (ALERTA DE SEGURANÇA)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luizhenriquegoncalves147@gmail.com
spring.mail.password=zdlthelrelhutfzn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*


# ===================================================================
# CONFIGURAÇÕES DE BLINDAGEM E SEGURANÇA DA API (OWASP REQS)
# ===================================================================
app.security.salt=${CONECTA_API_SALT:ConectaVida_SecretSalt_2026_IFSP}
app.security.allowed-origins=${CONECTA_CORS_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000,http://localhost:4000,http://localhost}

# ===================================================================
# FIREBASE CLOUD MESSAGING (PUSH NOTIFICATIONS)
# ===================================================================
fcm.server.key=${FCM_SERVER_KEY:COLOQUE_A_SERVER_KEY_AQUI}